'use client'

import {Container} from './styles';
import Nav from '../components/Nav';
import Button from '../components/Button';
import Note from '../components/Note';

export default function Home() {
    return(
        <Container>
            <Nav/>
            <main>
                <div class="title">
                    <h1>Meus filmes</h1>
                    <Button title="+ Adicionar filme"/>
                </div>

                <section>
                    <Note title="Interstellar" 
                    descriptionPreview="There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...
                    There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...
                    There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...
                    There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...
                    There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...
                    There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...
                    There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...
                    There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..."/>
                    
                    <Note title="Interstellar" 
                    descriptionPreview="There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...
                    There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...
                    There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...
                    There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...
                    There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...
                    There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...
                    There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...
                    There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..."/>

                    <Note title="Interstellar" 
                    descriptionPreview="There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...
                    There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...
                    There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...
                    There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...
                    There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...
                    There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...
                    There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...
                    There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..."/>
                    
                </section>
            </main>
        </Container>

    )
}